import Link from "next/link";
import { Header } from "@/components/site-client";
import { collections, editionsAndMedia, groupExhibitions, soloExhibitions, timeline } from "@/data/content";

export default function ParcoursPage(){return <main id="top" className="document-page"><Header/>
  <header className="page-intro shell"><p className="eyebrow">Parcours complet</p><h1>Biographie<br/><em>& inventaire</em></h1><p>Une chronologie documentaire étendue : formation, expositions, collections, éditions et médias. Les informations sont issues en priorité de DDAB et des fonds institutionnels.</p></header>
  <nav className="chapter-nav shell" aria-label="Sections du parcours"><a href="#biographie"><span>01</span>Biographie</a><a href="#expositions"><span>02</span>Expositions</a><a href="#collections"><span>03</span>Collections & éditions</a></nav>
  <section className="archive-section shell" id="biographie"><header className="archive-heading"><div><span>01</span><h2>Biographie vérifiée</h2></div><p>Le lieu de naissance reste contradictoire selon les sources.</p></header><div className="fact-list wide-facts">{timeline.map(([year,text])=><div key={year}><time>{year}</time><p>{text}</p></div>)}</div></section>
  <section className="archive-section shell" id="expositions"><header className="archive-heading"><div><span>02</span><h2>Expositions</h2></div><p>{soloExhibitions.length} personnelles · {groupExhibitions.length} collectives recensées en ligne</p></header><div className="inventory-columns"><div><h3>Personnelles</h3><div className="fact-list">{soloExhibitions.map(([year,text],i)=><div key={`${year}-${i}`}><time>{year}</time><p>{text}</p></div>)}</div></div><div><h3>Collectives</h3><div className="fact-list">{groupExhibitions.map(([year,text],i)=><div key={`${year}-${i}`}><time>{year}</time><p>{text}</p></div>)}</div></div></div></section>
  <section className="archive-section shell" id="collections"><header className="archive-heading"><div><span>03</span><h2>Collections, éditions & médias</h2></div><p>Présences institutionnelles et autres formes de production.</p></header><div className="collection-grid">{collections.map((item,i)=><div key={item}><span>{String(i+1).padStart(2,"0")}</span><p>{item}</p></div>)}</div><div className="media-grid">{editionsAndMedia.map(([type,text])=><article key={type}><h3>{type}</h3><p>{text}</p></article>)}</div></section>
  <aside className="document-note shell"><strong>Note documentaire</strong><p>AGORHA et Le Grand Café indiquent Rennes comme lieu de naissance ; le FDAC d’Ille-et-Vilaine et plusieurs documents du Frac indiquent Lamballe. Le site conserve cette contradiction au lieu de choisir arbitrairement.</p></aside>
  <nav className="page-next shell"><Link href="/projets">← Œuvres & projets</Link><Link href="/archives">Toutes les sources →</Link></nav>
</main>}
