import Link from "next/link";
import { Header } from "@/components/site-client";
import { projects } from "@/data/content";

const details: Record<string,{summary:string;links:Array<[string,string]>}> = {
  acsls:{summary:"Un inventaire quotidien de formes, gestes et accidents anonymes rencontrés dans l’espace public. Le projet déplace le regard plutôt qu’il ne fabrique un nouvel objet.",links:[["Instagram de l’artiste","https://www.instagram.com/jean_philippe_lemee/"],["L’Architiste — entretien 2026","https://www.larchitiste.com/jean-philippe-lemee-chercheur-dart-chitecture-au-coin-de-la-rue"]]},
  lieux:{summary:"Une géographie personnelle des communes d’Ille-et-Vilaine : places, églises, cafés, mairies, maisons, détails et conversations deviennent un abécédaire du proche.",links:[["L’Architiste — entretien 2026","https://www.larchitiste.com/jean-philippe-lemee-chercheur-dart-chitecture-au-coin-de-la-rue"],["Instagram de l’artiste","https://www.instagram.com/jean_philippe_lemee/"]]},
  duos:{summary:"Des œuvres associées deux par deux pour produire des échos formels, historiques ou affectifs. Le projet est présenté à la Galerie La Rotonde à Lanester en 2021.",links:[["Lanester — Reflets n°293","https://www.lanester.bzh/fileadmin/user_upload/01_Lanester/Documents/Reflets/OLD/2021/reflets_293.pdf"],["DDAB — bio-bibliographie","https://ddabretagne.org/fr/artistes/jean-philippe-lemee/bio-biblio"]]},
  tableaux:{summary:"Depuis 1989, chaque tableau suit une recette : choix d’une image, dessin confié à d’autres, sélection, agrandissement, couleurs puis réalisation par un peintre en lettres.",links:[["CNAP — CHIC Collection","https://www.cnap.fr/jean-philippe-lemee-0"],["DDAB — présentation","https://ddabretagne.org/fr/artistes/jean-philippe-lemee/presentation"]]},
  ncdgqad:{summary:"Créée avec Gilles Mahé, cette école de dessin par correspondance réunit 1 500 participants de 1994 à 1997, publie trente affiches-catalogues et constitue une boîte d’archives.",links:[["CNAP — Mécaniques du dessin","https://www.cnap.fr/mecaniques-du-dessin"],["DDAB — bio-bibliographie","https://ddabretagne.org/fr/artistes/jean-philippe-lemee/bio-biblio"]]},
  architecture:{summary:"Une lecture de l’architecture comme expérience vécue : seuils, parcours, alentours et usages composent une histoire sensible de l’espace construit.",links:[["L’Architiste — entretien 2026","https://www.larchitiste.com/jean-philippe-lemee-chercheur-dart-chitecture-au-coin-de-la-rue"],["Collection d’Ille-et-Vilaine","https://artcontemporain.ille-et-vilaine.fr/assets/040_jean-philippe-lemee.pdf"]]},
};

export default function ProjectsPage(){return <main id="top" className="document-page"><Header/><header className="document-hero shell"><div><span className="kicker">Dossiers</span><h1>Projets<br />& méthodes</h1></div><p>Six entrées synthétiques. Chaque projet est accompagné des sources qui permettent d’en vérifier ou d’en prolonger la lecture.</p></header><section className="project-records shell">{projects.map(project=><article id={project.id} key={project.id}><div className="record-id"><span>{project.number}</span><small>{project.category}</small></div><div className="record-main"><p className="record-subtitle">{project.subtitle}</p><h2>{project.title}</h2><p>{details[project.id].summary}</p></div><div className="record-sources"><span>Sources associées</span>{details[project.id].links.map(([label,url])=><a href={url} target="_blank" rel="noreferrer" key={url}>{label}<i>↗</i></a>)}</div></article>)}</section><nav className="page-next shell"><Link href="/">← Accueil</Link><Link href="/archives">Corpus complet →</Link></nav></main>}
